name: build-linux

on:
  push:
    branches: master
  # To be able to trigger a manual build
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Miniconda (Python ${{ matrix.python-version }})
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: pyani-github
          auto-activate-base: false
          channels: defaults,bioconda,conda-forge
          channel-priority: flexible

      - name: Check Miniconda Installation
        run: |
          conda info
          conda list

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install Development Requirements
        run: conda install --file requirements-dev.txt -y

      - name: Install Requirements
        run: conda install --file requirements.txt -y

      - name: Install third-party tools
        run: conda install --file requirements-thirdparty-linux.txt -y

      - name: Install and Check FastANI
        run: |
          conda install --file requirements-fastani-linux.txt -y
          fastani -h

      - name: Install PyQT
        run: conda install --file requirements-pyqt-conda.txt -y

      - name: Install pip requirements
        run: pip install -r requirements-pip.txt

      - name: Install pyani
        run: pip install -e .

      - name: Check pytest modules
        run: python -m pytest -v --collect-only

      - name: Run Tests with pytest
        run: python -m pytest -v --cov=pyani --cov-report=xml:.coverage-${{ matrix.python-version }}.xml

      - name: Upload coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage-${{ matrix.python-version }}
          path: .coverage-${{ matrix.python-version }}.xml
          retention-days: 1
        if: ${{ always() }}
