name: build-on-push-to-master

on:
  push:
    branches: master
  # To be able to trigger a manual build
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }} 
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.11"
          activate-environment: pyani-github
          auto-activate-base: false
          channels: defaults,bioconda,conda-forge
          channel-priority: flexible
        run: |
          conda info
          conda list

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install Development Requirements
        run: conda install --file requirements-dev.txt -y

      - name: Install Requirements
        run: conda install --file requirements.txt -y

      - name: Install third-party tools
        run: conda install --file requirements-thirdparty.txt -y

      - name: Install FastANI
        run: conda install --file requirements-fastani.txt -y

      - name: Install PyQT
        run: conda install --file requirements-pyqt-conda.txt -y

      - name: Install pip requirements
        run: pip install -r requirements-pip.txt

      - name: Install pyani
        run: pip install -e .

      - name: Check pytest modules
        run: python -m pytest -v --collect-only

      - name: Run Tests with pytest
        run: python -m pytest -v -m "not slow" --cov=pyani --cov-report=xml:.coverage_fast.xml

      - name: Upload coverage Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-3.11
          path: .coverage_fast.xml
          retention-days: 1
        if: ${{ always() }}
